version: '3.7'

services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  web:
    build: .
    command: gunicorn core.asgi:application -w 4 -k uvicorn.workers.UvicornWorker --reload --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
      - static:/usr/src/app/static
      - media:/usr/src/app/media
    expose:
      - 8000
    env_file:
      - ./.env.dev
    links:
      - redis
    environment: 
      - REDIS_URL=redis://cache
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=app
  nginx:
    build: ./nginx
    volumes:
      - static:/usr/src/app/static
      - media:/usr/src/app/media
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static:
  media: